# Generated by Django 3.1 on 2020-08-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_product',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
