# Generated by Django 3.1 on 2020-09-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200831_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='crawler',
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Crawler',
        ),
    ]
