# Generated by Django 3.1 on 2020-09-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_store_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_product',
            field=models.FloatField(max_length=20),
        ),
    ]
