# Generated by Django 3.1 on 2020-09-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200902_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price_product',
            field=models.FloatField(max_length=20),
        ),
    ]
