# Generated by Django 3.1 on 2020-09-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200910_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_image',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
