# Generated by Django 3.1 on 2020-09-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_product',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
