# Generated by Django 3.1 on 2020-10-01 02:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200916_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), null=True, size=10),
        ),
    ]
