# Generated by Django 3.1 on 2020-10-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200930_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_product',
            field=models.URLField(max_length=5000, unique=True),
        ),
    ]
